---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Receitas de cozinha
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Dados estatísticos de um país
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Dados individualizados de seus cidadãos
  checked: false
name: Aberto ao público
