---
locale: pt
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Receitas de cozinha
  checked: false
- value: Dados estatísticos de um país
  checked: true
- value: Dados individualizados de seus cidadãos
  checked: false
name: Aberto ao público
