---
locale: pt
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`livrarias["sector"].head(3)`'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`livrarias["city_name"].tail(4)`'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`len(livrarias["city_name"])`'
  checked: true
name: Uma coluna fora de série
