---
locale: pt
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Que os dados foram atualizados em 2018 e 2020
  checked: true
- value: Que em 2020 19 linhas foram atualizadas
  checked: true
- value: Que em 2018 19 linhas foram atualizadas
  checked: false
- value: Que em Chubut há 19 livrarias
  checked: true
- value: Que em San Luis há mais livrarias do que em Formosa
  checked: true
- value: Que em Catamarca há mais livrarias que em Jujuy
  checked: false
name: Diga-me
