---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Que os dados foram atualizados em 2018 e 2020
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Que em 2020 19 linhas foram atualizadas
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Que em 2018 19 linhas foram atualizadas
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Que em Chubut há 19 livrarias
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Que em San Luis há mais livrarias do que em Formosa
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Que em Catamarca há mais livrarias que em Jujuy
  checked: false
name: Diga-me
