---
locale: pt
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Mantém a ordem original, a qual parte do `0`
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Mantém a ordem original, a qual parte do `1`
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Altera a ordem original
  checked: true
goal: |
  --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_equals
  value: TODO
name: Arrume a bagunça, é uma ordem!
