---
locale: pt
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: O primeiro campo representa um nome ou apelido
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: O primeiro campo representa uma idade
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: O segundo campo representa a cidade de nascimento
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: O segundo campo representa um sobrenome
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: O terceiro campo representa uma data de nascimento
  checked: false
name: Mantendo as formas
