---
locale: pt
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`head` ordena segundo `loc_code` de forma ascendente"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`tail` ordena segundo `loc_code` de forma ascendente"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`head` ordena segundo `prov_id` de forma ascendente"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`tail` ordena segundo `prov_id` de forma descendente"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Todas as linhas devolvidas por `head` e `tail` nos exemplos têm em `category`
    o valor `Salas de cinema`
  checked: true
goal: |
  --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_matches
  regexp: cinemas.tail(\s*5\s*)\s*
name: Da cabeça aos pés
