---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: o operador `[]` retorna `None`
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: o operador `[]` produz um `KeyError`
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: o operador `[]` produz um `NameError`
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: o operador `[]` produz um `SyntaxError`
  checked: false
name: Acessando as colunas
