---
locale: pt
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Nada é exibido
  checked: false
- value: Aparece uma tabela
  checked: true
- value: Aparece um gráfico
  checked: false
- value: Ocorre um erro
  checked: false
goal: |
  --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_equals
  value: TODO
name: Carregando dados
